// Code generated by protoc-gen-go. DO NOT EDIT.
// source: supportbot.proto

package supportbot

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListEmailsRequest struct {
	Filter               string   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEmailsRequest) Reset()         { *m = ListEmailsRequest{} }
func (m *ListEmailsRequest) String() string { return proto.CompactTextString(m) }
func (*ListEmailsRequest) ProtoMessage()    {}
func (*ListEmailsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5896a2ffe760477b, []int{0}
}

func (m *ListEmailsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEmailsRequest.Unmarshal(m, b)
}
func (m *ListEmailsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEmailsRequest.Marshal(b, m, deterministic)
}
func (m *ListEmailsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEmailsRequest.Merge(m, src)
}
func (m *ListEmailsRequest) XXX_Size() int {
	return xxx_messageInfo_ListEmailsRequest.Size(m)
}
func (m *ListEmailsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEmailsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEmailsRequest proto.InternalMessageInfo

func (m *ListEmailsRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type ListEmailsResponse struct {
	Emails               []*Email `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEmailsResponse) Reset()         { *m = ListEmailsResponse{} }
func (m *ListEmailsResponse) String() string { return proto.CompactTextString(m) }
func (*ListEmailsResponse) ProtoMessage()    {}
func (*ListEmailsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5896a2ffe760477b, []int{1}
}

func (m *ListEmailsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEmailsResponse.Unmarshal(m, b)
}
func (m *ListEmailsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEmailsResponse.Marshal(b, m, deterministic)
}
func (m *ListEmailsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEmailsResponse.Merge(m, src)
}
func (m *ListEmailsResponse) XXX_Size() int {
	return xxx_messageInfo_ListEmailsResponse.Size(m)
}
func (m *ListEmailsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEmailsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEmailsResponse proto.InternalMessageInfo

func (m *ListEmailsResponse) GetEmails() []*Email {
	if m != nil {
		return m.Emails
	}
	return nil
}

type Email struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Subject              string   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_5896a2ffe760477b, []int{2}
}

func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Email) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Email) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Email) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ListEmailsRequest)(nil), "supportbot.ListEmailsRequest")
	proto.RegisterType((*ListEmailsResponse)(nil), "supportbot.ListEmailsResponse")
	proto.RegisterType((*Email)(nil), "supportbot.Email")
}

func init() { proto.RegisterFile("supportbot.proto", fileDescriptor_5896a2ffe760477b) }

var fileDescriptor_5896a2ffe760477b = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0x87, 0x69, 0x77, 0xad, 0x3a, 0xfe, 0xc1, 0x1d, 0x41, 0xc2, 0xa2, 0x52, 0x72, 0xaa, 0x0a,
	0x5b, 0x5c, 0x6f, 0x5e, 0x04, 0xc1, 0x9b, 0xa7, 0x7a, 0xf2, 0x66, 0xba, 0x66, 0xd7, 0x48, 0x37,
	0x13, 0x9b, 0xa9, 0x0f, 0xe0, 0x2b, 0xf8, 0x68, 0xbe, 0x82, 0x0f, 0x22, 0xa6, 0x95, 0x2d, 0xc8,
	0xde, 0x66, 0xbe, 0x7c, 0x49, 0x7e, 0x33, 0x70, 0xe0, 0x1b, 0xe7, 0xa8, 0xe6, 0x92, 0x78, 0xe2,
	0x6a, 0x62, 0x42, 0x58, 0x91, 0xf1, 0xf1, 0x82, 0x68, 0x51, 0xe9, 0x5c, 0x39, 0x93, 0x2b, 0x6b,
	0x89, 0x15, 0x1b, 0xb2, 0xbe, 0x35, 0xe5, 0x05, 0x8c, 0xee, 0x8d, 0xe7, 0xbb, 0xa5, 0x32, 0x95,
	0x2f, 0xf4, 0x5b, 0xa3, 0x3d, 0xe3, 0x11, 0x24, 0x73, 0x53, 0xb1, 0xae, 0x45, 0x94, 0x46, 0xd9,
	0x76, 0xd1, 0x75, 0xf2, 0x06, 0xb0, 0x2f, 0x7b, 0x47, 0xd6, 0x6b, 0x3c, 0x83, 0x44, 0x07, 0x22,
	0xa2, 0x74, 0x90, 0xed, 0x4c, 0x47, 0x93, 0x5e, 0x9e, 0xe0, 0x16, 0x9d, 0x20, 0x1f, 0x61, 0x23,
	0x00, 0x44, 0x18, 0xce, 0x6b, 0x5a, 0x76, 0xef, 0x87, 0x1a, 0xf7, 0x21, 0x66, 0x12, 0x71, 0x20,
	0x31, 0x13, 0x0a, 0xd8, 0xf4, 0x4d, 0xf9, 0xaa, 0x67, 0x2c, 0x06, 0x01, 0xfe, 0xb5, 0xbf, 0xb7,
	0x9f, 0x15, 0x2b, 0x31, 0x4c, 0xa3, 0x6c, 0xb7, 0x08, 0xf5, 0xd4, 0x02, 0x3c, 0xb4, 0xdf, 0xde,
	0x12, 0xe3, 0x13, 0xc0, 0x2a, 0x29, 0x9e, 0xf4, 0x13, 0xfd, 0x1b, 0x77, 0x7c, 0xba, 0xee, 0xb8,
	0x1d, 0x50, 0x1e, 0x7e, 0x7c, 0x7d, 0x7f, 0xc6, 0x7b, 0x72, 0x2b, 0x7f, 0xbf, 0xcc, 0xf5, 0xec,
	0x85, 0xae, 0xa3, 0xf3, 0x32, 0x09, 0xfb, 0xbb, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xa4,
	0x72, 0x30, 0x7d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SupportBotClient is the client API for SupportBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SupportBotClient interface {
	ListEmails(ctx context.Context, in *ListEmailsRequest, opts ...grpc.CallOption) (*ListEmailsResponse, error)
}

type supportBotClient struct {
	cc *grpc.ClientConn
}

func NewSupportBotClient(cc *grpc.ClientConn) SupportBotClient {
	return &supportBotClient{cc}
}

func (c *supportBotClient) ListEmails(ctx context.Context, in *ListEmailsRequest, opts ...grpc.CallOption) (*ListEmailsResponse, error) {
	out := new(ListEmailsResponse)
	err := c.cc.Invoke(ctx, "/supportbot.SupportBot/ListEmails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupportBotServer is the server API for SupportBot service.
type SupportBotServer interface {
	ListEmails(context.Context, *ListEmailsRequest) (*ListEmailsResponse, error)
}

// UnimplementedSupportBotServer can be embedded to have forward compatible implementations.
type UnimplementedSupportBotServer struct {
}

func (*UnimplementedSupportBotServer) ListEmails(ctx context.Context, req *ListEmailsRequest) (*ListEmailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEmails not implemented")
}

func RegisterSupportBotServer(s *grpc.Server, srv SupportBotServer) {
	s.RegisterService(&_SupportBot_serviceDesc, srv)
}

func _SupportBot_ListEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEmailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupportBotServer).ListEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supportbot.SupportBot/ListEmails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupportBotServer).ListEmails(ctx, req.(*ListEmailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SupportBot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "supportbot.SupportBot",
	HandlerType: (*SupportBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEmails",
			Handler:    _SupportBot_ListEmails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supportbot.proto",
}
